server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/product_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: senha123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
      auto-commit: true
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true

#  elasticsearch:
#    uris: http://elasticsearch:9200

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: product-service-group

jwt:
  secret: MINHA_CHAVE_SECRETA_AQUI_UMA_STRING_GRANDE_E_SEGURA
  expiration: 3600000  # 1 hora